setwd("C:/Users/Ichchhayakant/Desktop/LAB/ML Lab")
data <- read.csv("census.csv")
View(data)
str(data)
library(caTools)
set.seed(3000)
library(pROC)
library(rpart)
library(rpart.plot)
sapply(data, function(x) sum(is.na(x)))

### Spliting data 
spl <- sample.split(data$over50k, SplitRatio = 0.6)
train <- subset(data,spl==T)
test <- subset(data, spl==F)
table(test$over50k)
Cart <- rpart(over50k~.,train,method='class')
prp(Cart)
predictCart <- predict(Cart,test, method='class')
table(test$over50k,predictCart)
nrow(test$over50k)
dim(predictCart)
dim(test)
